grubfood/urls.py
from django.contrib import admin

from django.urls import include, path

urlpatterns = [
    path('webkiosk/', include('webkiosk.urls')),
    path('admin/', admin.site.urls),
]

webkiosk/urls.py
from django.urls import path

from . import views

app_name = 'webkiosk'
urlpatterns = [
    path('', views.index, name='index'),

    path('foods', views.foods_index, name='foods_index'),
    path('foods/new', views.foods_new, name='foods_new'),
    path('foods/create', views.foods_create, name='foods_create'),
    path('foods/<int:food_id>', views.foods_show, name='foods_show'),
    path('foods/<int:food_id>/edit', views.foods_edit, name='foods_edit'),
    path('foods/<int:food_id>/update', views.foods_update, name='foods_update'),
    path('foods/<int:food_id>/delete',
         views.foods_delete, name='foods_delete'),
    path('foods/<int:food_id>/destroy',
         views.foods_destroy, name='foods_destroy'),

    path('customers', views.customers_index, name='customers_index'),
    path('customers/new', views.customers_new, name='customers_new'),
    path('customers/create', views.customers_create, name='customers_create'),
    path('customers/<int:customer_id>',
         views.customers_show, name='customers_show'),
    path('customers/<int:customer_id>/edit',
         views.customers_edit, name='customers_edit'),
    path('customers/<int:customer_id>/update',
         views.customers_update, name='customers_update'),
    path('customers/<int:customer_id>/delete',
         views.customers_delete, name='customers_delete'),
    path('customers/<int:customer_id>/destroy',
         views.customers_destroy, name='customers_destroy'),

    path('orders', views.orders_index, name='orders_index'),
    path('orders/new', views.orders_new, name='orders_new'),
    path('orders/create', views.orders_create, name='orders_create'),
    path('orders/<int:order_id>', views.orders_show, name='orders_show'),
    path('orders/<int:order_id>/edit', views.orders_edit, name='orders_edit'),
    path('orders/<int:order_id>/update',
         views.orders_update, name='orders_update'),
    path('orders/<int:order_id>/delete',
         views.orders_delete, name='orders_delete'),
    path('orders/<int:order_id>/destroy',
         views.orders_destroy, name='orders_destroy'),

    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

webkiosk/models.py
from django.db import models
from datetime import datetime


class Food(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f'[{self.pk}] {self.name}, {self.description}, {self.price}'


class Customer(models.Model):
    firstname = models.CharField(max_length=200, verbose_name='first name')
    lastname = models.CharField(max_length=200, verbose_name='last name')
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)

    def __str__(self):
        return f'[{self.pk}] {self.firstname} {self.lastname}, {self.address}, {self.city}'

    def orders(self):
        return self.order_set.all()


class Order(models.Model):
    PAYMENT_CHOICES = [
        ('Cash', 'Cash'),
        ('Card', 'Card'),
    ]

    orderdatetime = models.DateTimeField(
        default=datetime.now(), verbose_name='date and time')
    paymentmode = models.CharField(
        max_length=4, choices=PAYMENT_CHOICES, verbose_name='payment mode')
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return f'[{self.pk}] {self.customer.firstname} {self.customer.lastname}, {self.food.name}, {self.quantity}, {self.orderdatetime}'

    def totalprice(self):
        return self.quantity * self.food.price

webkiosk/forms.py
from django.forms import ModelForm, widgets
from .models import Food, Customer, Order


class FoodForm(ModelForm):
    class Meta:
        model = Food
        fields = '__all__'


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

webkiosk/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.contrib.auth import authenticate as django_authenticate, login as django_login, logout as django_logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect


from .forms import FoodForm, CustomerForm, OrderForm
from .models import Food, Customer, Order


def index(request):
    return render(request, 'webkiosk/index.html')


@login_required(login_url='/webkiosk/login')
def foods_index(request):
    foods = Food.objects.order_by('pk')
    context = {'foods': foods}
    return render(request, 'webkiosk/foods/index.html', context)


@login_required(login_url='/webkiosk/login')
def foods_show(request, food_id):
    food = get_object_or_404(Food, pk=food_id)
    context = {'food': food}
    return render(request, 'webkiosk/foods/show.html', context)


@login_required(login_url='/webkiosk/login')
def foods_new(request):
    form = FoodForm()
    context = {'form': form}
    return render(request, 'webkiosk/foods/new.html', context)


@login_required(login_url='/webkiosk/login')
def foods_create(request):
    if request.method == 'POST':
        form = FoodForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('webkiosk:foods_index'))
    else:
        return HttpResponseRedirect(reverse('webkiosk:foods_new'))


@login_required(login_url='/webkiosk/login')
def foods_edit(request, food_id):
    food = get_object_or_404(Food, pk=food_id)
    form = FoodForm(instance=food)
    context = {'form': form, 'food_id': food_id}
    return render(request, 'webkiosk/foods/edit.html', context)


@login_required(login_url='/webkiosk/login')
def foods_update(request, food_id):
    food = get_object_or_404(Food, pk=food_id)
    if request.method == 'POST':
        form = FoodForm(request.POST, instance=food)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('webkiosk:foods_index'))
    else:
        return HttpResponseRedirect(reverse('webkiosk:foods_edit', args=(food_id,)))


@login_required(login_url='/webkiosk/login')
def foods_delete(request, food_id):
    food = get_object_or_404(Food, pk=food_id)
    context = {'food': food}
    return render(request, 'webkiosk/foods/delete.html', context)


@login_required(login_url='/webkiosk/login')
def foods_destroy(request, food_id):
    food = get_object_or_404(Food, pk=food_id)
    if request.method == 'POST':
        food.delete()
        return HttpResponseRedirect(reverse('webkiosk:foods_index'))
    else:
        return HttpResponseRedirect(reverse('webkiosk:foods_delete', args=(food_id,)))


@login_required(login_url='/webkiosk/login')
def customers_index(request):
    customers = Customer.objects.order_by('pk')
    context = {'customers': customers}
    return render(request, 'webkiosk/customers/index.html', context)


@login_required(login_url='/webkiosk/login')
def customers_show(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    context = {'customer': customer}
    return render(request, 'webkiosk/customers/show.html', context)


@login_required(login_url='/webkiosk/login')
def customers_new(request):
    form = CustomerForm()
    context = {'form': form}
    return render(request, 'webkiosk/customers/new.html', context)


@login_required(login_url='/webkiosk/login')
def customers_create(request):
    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('webkiosk:customers_index'))
    else:
        return HttpResponseRedirect(reverse('webkiosk:customers_new'))


@login_required(login_url='/webkiosk/login')
def customers_edit(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    form = CustomerForm(instance=customer)
    context = {'form': form, 'customer_id': customer_id}
    return render(request, 'webkiosk/customers/edit.html', context)


@login_required(login_url='/webkiosk/login')
def customers_update(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    if request.method == 'POST':
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('webkiosk:customers_index'))
    else:
        return HttpResponseRedirect(reverse('webkiosk:customers_edit', args=(customer_id,)))


@login_required(login_url='/webkiosk/login')
def customers_delete(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    context = {'customer': customer}
    return render(request, 'webkiosk/customers/delete.html', context)


@login_required(login_url='/webkiosk/login')
def customers_destroy(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    if request.method == 'POST':
        customer.delete()
        return HttpResponseRedirect(reverse('webkiosk:customers_index'))
    else:
        return HttpResponseRedirect(reverse('webkiosk:customers_delete', args=(customer_id,)))


@login_required(login_url='/webkiosk/login')
def orders_index(request):
    orders = Order.objects.order_by('pk')
    context = {'orders': orders}
    return render(request, 'webkiosk/orders/index.html', context)


@login_required(login_url='/webkiosk/login')
def orders_show(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    context = {'order': order}
    return render(request, 'webkiosk/orders/show.html', context)


@login_required(login_url='/webkiosk/login')
def orders_new(request):
    form = OrderForm()
    context = {'form': form}
    return render(request, 'webkiosk/orders/new.html', context)


@login_required(login_url='/webkiosk/login')
def orders_create(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('webkiosk:orders_index'))
    else:
        return HttpResponseRedirect(reverse('webkiosk:orders_new'))


@login_required(login_url='/webkiosk/login')
def orders_edit(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    form = OrderForm(instance=order)
    context = {'form': form, 'order_id': order_id}
    return render(request, 'webkiosk/orders/edit.html', context)


@login_required(login_url='/webkiosk/login')
def orders_update(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    if request.method == 'POST':
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('webkiosk:orders_index'))
    else:
        return HttpResponseRedirect(reverse('webkiosk:orders_edit', args=(order_id,)))


@login_required(login_url='/webkiosk/login')
def orders_delete(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    context = {'order': order}
    return render(request, 'webkiosk/orders/delete.html', context)


@login_required(login_url='/webkiosk/login')
def orders_destroy(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    if request.method == 'POST':
        order.delete()
        return HttpResponseRedirect(reverse('webkiosk:orders_index'))
    else:
        return HttpResponseRedirect(reverse('webkiosk:orders_delete', args=(order_id,)))


def login(request):
    if request.method == 'GET':
        return render(request, 'webkiosk/login.html')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = django_authenticate(
            request, username=username, password=password)
        if user is not None:
            django_login(request, user)
            return HttpResponseRedirect(reverse('webkiosk:foods_index'))
        else:
            return HttpResponseRedirect(reverse('webkiosk:login'))


def logout(request):
    django_logout(request)
    return HttpResponseRedirect(reverse('webkiosk:index'))


def authenticate(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('webkiosk:index'))

webkiosk/templates/webkiosk/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>grubfood</title>
    <link rel="stylesheet" href="{% static 'webkiosk/index.css' %}" />
    <link rel="icon" href="{% static 'webkiosk/images/logo.svg' %}" />
  </head>
  <body>
    <nav>
      <div>
        <a href="{% url 'webkiosk:index' %}" class="logo">
          <img src="{% static 'webkiosk/images/logo.svg' %}" alt="logo" />
          <span>grubfood</span>
        </a>
        {% if request.user.is_authenticated %}
        <ul>
          <li><a href="{% url 'webkiosk:foods_index' %}">Foods</a></li>
          <li><a href="{% url 'webkiosk:customers_index' %}">Customers</a></li>
          <li><a href="{% url 'webkiosk:orders_index' %}">Orders</a></li>
        </ul>
        {% endif %}
      </div>
      {% if request.user.is_authenticated %}
      <form action="{% url 'webkiosk:logout' %}">
        {% csrf_token %}
        <input type="submit" value="Log out" class="button-secondary" />
      </form>
      {% else %}
      <a href="{% url 'webkiosk:login' %}">
        <button class="button-secondary">Log in</button>
      </a>
      {% endif %}
    </nav>
    {% block body %}{% endblock body %}
  </body>
</html>

webkiosk/templates/webkiosk/customers_index.html
<h1>Customers</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Full Name</th>
    <th>City</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  {% for customer in customers %}
  <tr>
    <td>{{ customer.pk }}</td>
    <td>{{ customer.firstname }} {{ customer.lastname }}</td>
    <td>{{ customer.city }}</td>
    <td><a href="">Show</a></td>
    <td><a href="">Edit</a></td>
    <td><a href="">Delete</a></td>
  </tr>
  {% endfor %}
</table>

<a href="">Add Customer</a>

webkiosk/templates/webkiosk/foods_index.html
<h1>Foods</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  {% for food in foods %}
  <tr>
    <td>{{ food.pk }}</td>
    <td>{{ food.name }}</td>
    <td>{{ food.price }}</td>
    <td><a href="">Show</a></td>
    <td><a href="">Edit</a></td>
    <td><a href="">Delete</a></td>
  </tr>
  {% endfor %}
</table>

<a href="">Add Food</a>

webkiosk/templates/webkiosk/index.html
{% extends 'webkiosk/base.html' %} {% block body %}

<main class="wide">
  <section class="hero">
    <h1>grubfood</h1>
    <p>
      grubfood is Northwest Asia's leading food delivery service - delivering
      food and drinks to trillions of consumers every day.
    </p>
  </section>
  <section id="why-grub" class="box">
    <h2>Why choose grubfood</h2>
    <h3>More variety</h3>
    <p>
      Because we bully our partner restaurants into signing exclusive deals with
      us by threatening to remove them from our platform with trillions of daily
      users, grubfood has more variety than any of its competitors by a
      landslide. Explore our restaurants and find your new favorites!
    </p>
    <h3>Cheaper</h3>
    <p>
      You deliveries are subsidized by the VCs backing us! Even if we burn more
      and more money each year, our growth rises at the same rate so investors
      are happy. Deals on grubfood are so good that sometimes we even pay you to
      get food delivered!
    </p>
  </section>
</main>
<footer>
  <div id="footer-grub-technologies">
    <span><b>Grub Technologies</b></span>
    <span>Really Tall Tower</span>
    <span>42 Street Avenue</span>
    <span>No Name City</span>
  </div>
  <div>
    <span><b>grubfood</b></span>
    <span>News</span>
    <span>App</span>
    <span>What's New</span>
    <span>For Business</span>
    <span>Environment</span>
  </div>
  <div>
    <span><b>grubmart</b></span>
    <span>News</span>
    <span>App</span>
    <span>What's New</span>
    <span>For Business</span>
    <span>Environment</span>
  </div>
  <div>
    <span><b>grubrewards</b></span>
    <span>News</span>
    <span>App</span>
    <span>What's New</span>
    <span>For Business</span>
    <span>Environment</span>
  </div>
  <div>
    <span><b>grubexpress</b></span>
    <span>News</span>
    <span>App</span>
    <span>What's New</span>
    <span>For Business</span>
    <span>Environment</span>
  </div>
  <div>
    <span><b>grubpay</b></span>
    <span>News</span>
    <span>App</span>
    <span>What's New</span>
    <span>For Business</span>
    <span>Environment</span>
  </div>
  <div>
    <span><b>grubgifts</b></span>
    <span>News</span>
    <span>App</span>
    <span>What's New</span>
    <span>For Business</span>
    <span>Environment</span>
  </div>
</footer>

{% endblock body %}

webkiosk/templates/webkiosk/login.html
{% extends 'webkiosk/base.html' %} {% block body %}

<main>
  <div class="box">
    <h1>Log in</h1>
    <form action="{% url 'webkiosk:login' %}" method="post">
      {% csrf_token %}
      <div>
        <label for="username">Username</label>
        <input type="text" id="username" name="username" />
      </div>
      <div>
        <label for="password">Password</label>
        <input type="password" id="password" name="password" />
      </div>
      <div class="align-right">
        <a href="customers/customers.html">
          <button class="button-primary">Log in</button>
        </a>
      </div>
    </form>
  </div>
</main>

{% endblock body %}

webkiosk/templates/webkiosk/orders_index.html
<h1>Orders</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Customer's Full Name</th>
    <th>Date and Time of Order</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  {% for order in orders %}
  <tr>
    <td>{{ order.pk }}</td>
    <td>{{ order.customer.firstname }} {{ order.customer.lastname }}</td>
    <td>{{ order.orderdatetime }}</td>
    <td><a href="">Show</a></td>
    <td><a href="">Edit</a></td>
    <td><a href="">Delete</a></td>
  </tr>
  {% endfor %}
</table>

<a href="">Add Order</a>